# SPDX-License-Identifier: GPL-2.0

# Enable W=1
subdir-ccflags-y := $(KBUILD_CFLAGS_W1)

obj-$(CONFIG_VDPA) += vdpa.o
obj-$(CONFIG_VDPA_SIM) += vdpa_sim/
obj-$(CONFIG_IFCVF)    += ifcvf/
obj-$(CONFIG_MLX5_VDPA) += mlx5/
