# SPDX-License-Identifier: GPL-2.0-only
#
# Makefile for the SLIP network device drivers.
#

# Enable W=1
subdir-ccflags-y := $(KBUILD_CFLAGS_W1)

obj-$(CONFIG_SLIP) += slip.o
obj-$(CONFIG_SLHC) += slhc.o
