/* SPDX-License-Identifier: GPL-2.0 WITH Linux-syscall-note */
/*
 * include/uapi/linux/ethtool_netlink.h - netlink interface for ethtool
 *
 * See Documentation/networking/ethtool-netlink.txt in kernel source tree for
 * doucumentation of the interface.
 */

#ifndef _UAPI_LINUX_ETHTOOL_NETLINK_H_
#define _UAPI_LINUX_ETHTOOL_NETLINK_H_

#include <linux/ethtool.h>

enum {
	ETHNL_CMD_NOOP,
	ETHNL_CMD_EVENT,		/* only for notifications */
	ETHNL_CMD_GET_STRSET,
	ETHNL_CMD_SET_STRSET,		/* only for reply */
	ETHNL_CMD_GET_INFO,
	ETHNL_CMD_SET_INFO,		/* only for reply */

	__ETHNL_CMD_CNT,
	ETHNL_CMD_MAX = (__ETHNL_CMD_CNT - 1)
};

/* device specification */

enum {
	ETHTOOL_A_DEV_UNSPEC,
	ETHTOOL_A_DEV_INDEX,			/* u32 */
	ETHTOOL_A_DEV_NAME,			/* string */

	__ETHTOOL_A_DEV_CNT,
	ETHTOOL_A_DEV_MAX = (__ETHTOOL_A_DEV_CNT - 1)
};

/* bit sets */

enum {
	ETHTOOL_A_BIT_UNSPEC,
	ETHTOOL_A_BIT_INDEX,			/* u32 */
	ETHTOOL_A_BIT_NAME,			/* string */
	ETHTOOL_A_BIT_VALUE,			/* flag */

	__ETHTOOL_A_BIT_CNT,
	ETHTOOL_A_BIT_MAX = (__ETHTOOL_A_BIT_CNT - 1)
};

enum {
	ETHTOOL_A_BITS_UNSPEC,
	ETHTOOL_A_BITS_BIT,

	__ETHTOOL_A_BITS_CNT,
	ETHTOOL_A_BITS_MAX = (__ETHTOOL_A_BITS_CNT - 1)
};

enum {
	ETHTOOL_A_BITSET_UNSPEC,
	ETHTOOL_A_BITSET_LIST,			/* flag */
	ETHTOOL_A_BITSET_SIZE,			/* u32 */
	ETHTOOL_A_BITSET_BITS,			/* nest - ETHTOOL_A_BITS_* */
	ETHTOOL_A_BITSET_VALUE,			/* binary */
	ETHTOOL_A_BITSET_MASK,			/* binary */

	__ETHTOOL_A_BITSET_CNT,
	ETHTOOL_A_BITSET_MAX = (__ETHTOOL_A_BITSET_CNT - 1)
};

/* events */

enum {
	ETHTOOL_A_NEWDEV_UNSPEC,
	ETHTOOL_A_NEWDEV_DEV,			/* nest - ETHTOOL_A_DEV_* */

	__ETHTOOL_A_NEWDEV_CNT,
	ETHTOOL_A_NEWDEV_MAX = (__ETHTOOL_A_NEWDEV_CNT - 1)
};

enum {
	ETHTOOL_A_DELDEV_UNSPEC,
	ETHTOOL_A_DELDEV_DEV,			/* nest - ETHTOOL_A_DEV_* */

	__ETHTOOL_A_DELDEV_CNT,
	ETHTOOL_A_DELDEV_MAX = (__ETHTOOL_A_DELDEV_CNT - 1)
};

enum {
	ETHTOOL_A_RENAMEDEV_UNSPEC,
	ETHTOOL_A_RENAMEDEV_DEV,		/* nest - ETHTOOL_A_DEV_* */

	__ETHTOOL_A_RENAMEDEV_CNT,
	ETHTOOL_A_RENAMEDEV_MAX = (__ETHTOOL_A_RENAMEDEV_CNT - 1)
};

enum {
	ETHTOOL_A_EVENT_UNSPEC,
	ETHTOOL_A_EVENT_NEWDEV,			/* nest - ETHTOOL_A_NEWDEV_* */
	ETHTOOL_A_EVENT_DELDEV,			/* nest - ETHTOOL_A_DELDEV_* */
	ETHTOOL_A_EVENT_RENAMEDEV,		/* nest - ETHTOOL_A_RENAMEDEV_* */

	__ETHTOOL_A_EVENT_CNT,
	ETHTOOL_A_EVENT_MAX = (__ETHTOOL_A_EVENT_CNT - 1)
};

/* string sets */

enum {
	ETHTOOL_A_STRING_UNSPEC,
	ETHTOOL_A_STRING_INDEX,			/* u32 */
	ETHTOOL_A_STRING_VALUE,			/* string */

	__ETHTOOL_A_STRING_CNT,
	ETHTOOL_A_STRING_MAX = (__ETHTOOL_A_STRING_CNT - 1)
};

enum {
	ETHTOOL_A_STRINGS_UNSPEC,
	ETHTOOL_A_STRINGS_STRING,		/* nest - ETHTOOL_A_STRINGS_* */

	__ETHTOOL_A_STRINGS_CNT,
	ETHTOOL_A_STRINGS_MAX = (__ETHTOOL_A_STRINGS_CNT - 1)
};

enum {
	ETHTOOL_A_STRINGSET_UNSPEC,
	ETHTOOL_A_STRINGSET_ID,			/* u32 */
	ETHTOOL_A_STRINGSET_COUNT,		/* u32 */
	ETHTOOL_A_STRINGSET_STRINGS,		/* nest - ETHTOOL_A_STRINGS_* */

	__ETHTOOL_A_STRINGSET_CNT,
	ETHTOOL_A_STRINGSET_MAX = (__ETHTOOL_A_STRINGSET_CNT - 1)
};

/* GET_STRINGSET / SET_STRINGSET */

enum {
	ETHTOOL_A_STRSET_UNSPEC,
	ETHTOOL_A_STRSET_DEV,			/* nest - ETHTOOL_A_DEV_* */
	ETHTOOL_A_STRSET_COUNTS,		/* flag */
	ETHTOOL_A_STRSET_STRINGSET,		/* nest - ETHTOOL_A_STRSET_* */

	__ETHTOOL_A_STRSET_CNT,
	ETHTOOL_A_STRSET_MAX = (__ETHTOOL_A_STRSET_CNT - 1)
};

/* GET_INFO / SET_INFO */

enum {
	ETHTOOL_A_INFO_UNSPEC,
	ETHTOOL_A_INFO_DEV,			/* nest - ETHTOOL_A_DEV_* */
	ETHTOOL_A_INFO_INFOMASK,		/* u32 */
	ETHTOOL_A_INFO_COMPACT,			/* flag */
	ETHTOOL_A_INFO_DRVINFO,			/* nest - ETHTOOL_A_DRVINFO_* */
	ETHTOOL_A_INFO_TSINFO,			/* nest - ETHTOOL_A_TSINFO_* */

	__ETHTOOL_A_INFO_CNT,
	ETHTOOL_A_INFO_MAX = (__ETHTOOL_A_INFO_CNT - 1)
};

#define ETHTOOL_IM_INFO_DRVINFO			(1U << 0)
#define ETHTOOL_IM_INFO_TSINFO			(1U << 1)

#define ETHTOOL_IM_INFO_ALL (ETHTOOL_IM_INFO_DRVINFO | \
			     ETHTOOL_IM_INFO_TSINFO)

enum {
	ETHTOOL_A_DRVINFO_UNSPEC,
	ETHTOOL_A_DRVINFO_DRIVER,		/* string */
	ETHTOOL_A_DRVINFO_FWVERSION,		/* string */
	ETHTOOL_A_DRVINFO_BUSINFO,		/* string */
	ETHTOOL_A_DRVINFO_EROM_VER,		/* string */

	__ETHTOOL_A_DRVINFO_CNT,
	ETHTOOL_A_DRVINFO_MAX = (__ETHTOOL_A_DRVINFO_CNT - 1)
};

enum {
	ETHTOOL_A_TSINFO_UNSPEC,
	ETHTOOL_A_TSINFO_TIMESTAMPING,		/* bitset */
	ETHTOOL_A_TSINFO_PHC_INDEX,		/* u32 */
	ETHTOOL_A_TSINFO_TX_TYPES,		/* bitset */
	ETHTOOL_A_TSINFO_RX_FILTERS,		/* bitset */

	__ETHTOOL_A_TSINFO_CNT,
	ETHTOOL_A_TSINFO_MAX = (__ETHTOOL_A_TSINFO_CNT - 1)
};

/* generic netlink info */
#define ETHTOOL_GENL_NAME "ethtool"
#define ETHTOOL_GENL_VERSION 1

#define ETHTOOL_MCGRP_MONITOR_NAME "monitor"

#endif /* _UAPI_LINUX_ETHTOOL_NETLINK_H_ */
